import React from "react";

import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";

import {Container, Stack, ThemeProvider} from "@mui/material";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter'
import {UserProvider} from "@/context/UserContext";
import theme from '@/theme'
import NavigationBar from "@/components/NavigationBar";
import Footer from "@/components/Footer";
import ReactQueryProvider from "@/context/ReactQueryProvider";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
                <ReactQueryProvider>
                    <UserProvider>
                        <Stack justifyContent="flex-start">
                            <NavigationBar/>
                            <Stack flexGrow={1} justifyContent="center" alignItems="center" minHeight="75vh">
                                <Container sx={{margin: 4}}>
                                    {children}
                                </Container>
                            </Stack>
                            <Footer/>
                        </Stack>
                    </UserProvider>
                </ReactQueryProvider>
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    )
}

